// ==========================================================================
// $Workfile:   EMMENU.H  $
// $Revision:   1.0  $
//
// HISTORY:
// Author            Date      Description
// --------------------------------------------------------------------------
//
//
//
// DESCRIPTION
// ==========================================================================
//   Copyright 1996 TeCom Inc. All rights reserved
// ==========================================================================

extern int in_energy_monitor;
extern int in_7_min_monitor;
extern int emon_device_idx;

void EnergyMonitorMenu(void);
void emon_horizontal_graph(void);
